### ISSUE TITLE
Where do I specify the location of the source PNG?

### ISSUE THREAD

**Issue by veilside1030** [EgonOlsen71/petsciiator#1]
Unless I'm very much mistaken, I don't think you mentioned where in the batch file I can specify the source file or directory... How do I do it? Thanks a lot!

**Comment by EgonOlsen71** [comment]
You just put the path in the call, without any additional parameter.

**Comment by EgonOlsen71** [comment]
There's also an experimental web version available (running on a Raspi 3b in my attic, so don't expect ultra performance): https://jpct.de/petscii
