### ISSUE TITLE
works!

### ISSUE THREAD

**Issue by zartan9** [EgonOlsen71/petsciiator#3]
great! is there a way to control the line numbers? I tested a picture and it starts at 60000?!  Thanks great software.

**Comment by EgonOlsen71** [comment]
It's hard coded into https://github.com/EgonOlsen71/petsciiator/blob/master/src/main/java/com/sixtyfour/petscii/Bitmap.java at the moment. One could modify that class and recompile, but I'm not sure if that's worth the hassle. Might be easier to use a renumber tool on the code generated.

**Comment by zartan9** [comment]
ok thanks p.s. is there a way to get a maze algorithm result? just an idea. thanks again.

**Comment by EgonOlsen71** [comment]
Not sure what you mean by that...!?

**Comment by zartan9** [comment]
oh i just mean can this work for mazes too? I havent tried yet but i may put in a maze picturre and see the result! thanks.

**Comment by EgonOlsen71** [comment]
I don't see why not...

**Comment by zartan9** [comment]
great thanks
    On Thursday, July 13, 2023 at 06:32:19 AM EDT, EgonOlsen ***@***.***> wrote:  
 
 


I don't see why not...
