### ISSUE TITLE
input!

### ISSUE THREAD

**Issue by zartan9** [EgonOlsen71/petsciiator#5]
hi ! I was looking for a img2 petscii maker that allows input. I tweaked it a bit so when user pressed letter A it goes to more text. My question is can i keep making petscii basic code (and changing the codeline numbers) to make sorta a slide show on A key pressed? do i have to recopy the poke code (im new to this) thanks!?

**Comment by EgonOlsen71** [comment]
So you want to create BASIC code based on some image that POKEs the PETSCII image onto the screen just like Petsciiator can do it but you want to combine multiple images into one large BASIC code snippet?

**Comment by zartan9** [comment]
yes im trying different ideas. its starting to work here: https://github.com/mkeke/c64-image-to-petscii/issues/1 but just seeing if possible with petscilator too 
thanks

**Comment by EgonOlsen71** [comment]
The line numbers are hard coded ATM. It would be possible to make them user defined, I'm just not convinced that this is the best option. It might be easier to use the .bbs-files that Petsciiactor also creates. These contain color and character information ready to be printed out to create the final image, i.e. you can do something like this (not tested, might contain a typo):

```
10 open 2,8,2,"image.bbs,s"
20 get#2,a$:print a$;
30 if st=0 then 20
40 close 2
```

to load the images one after the other from disk. All you need in addition is to set the background color, which isn't part of the file unfortunately.

**Comment by zartan9** [comment]
ah im not proficient enough, i cant find bbs just bas and seq files... i guess id need a working example where i could just add images. I picture about 40  petsci "images" in total...would that be under the file size limit ?

**Comment by EgonOlsen71** [comment]
You can produce files in bbs format like so:

`petscii.cmd /format=bbs <yourfile>.jpg`

You have to note the background color used (or specified by your call). Then rename the images to "image number" and drop them as seq-files onto a disk image. Then use something like the viewer program in the attached example to load them.
The viewer program stores the background color in DATA lines. For each new image, it reads the color (and stops when it reads -1), changes the background and loads the next image.

The disk image also contains a compiled version created using https://jpct.de/mospeed

Hope this helps.

[petscii.zip](https://github.com/EgonOlsen71/petsciiator/files/12726256/petscii.zip)

**Comment by zartan9** [comment]
thank you.
